export enum EnquiryStatusEnum {
  ENQUIRY_SENT = 'ENQUIRY_SENT',
  ENQUIRY_SEEN = 'ENQUIRY_SEEN',
  AGENT_CALLING = 'AGENT_CALLING',
  SOLUTION_PROVIDED = 'SOLUTION_PROVIDED',
  ENQUIRY_CLOSED = 'ENQUIRY_CLOSED',
}
