export enum OrderStatus {
  PENDING = "pending",
  PLACED = "placed",
  DELIVERED = "delivered",
  DISPATCH = "dispatch",
  RETURN = "return",
  CANCELLED = "cancelled",
  REJECTED = "rejected",
  RETURN_ACCEPTED = "return_accepted",
  RETURN_REJECTED = "return_rejected",
  RETURN_INITIATED = "return_initiated",
  NO_SERVICE = "no_service",
  CONFIRMED = "confirmed",
  IN_TRANSIT = "inTransit",
  REFUND_PRICE = "refund_price",
  REPLACEMENT_ORDER = "replacement_order",
  RTW_DAMAGE = "rtw_damage",
  RTW_RTO = "rtw_rto",
  COMPLETED = "completed",
  PROCESSING = "processing",
  APPROVAL_PENDING = "approval_pending",
  APPROVAL_REJECTED = "approval_rejected",
  Return_Intransit = "return_intransit",
}
