export enum ShippingStatus {
  PENDING = 'pending',
  PLACED = 'placed',
  DELIVERED = 'delivered',
  DISPATCH = 'dispatch',
  RETURN = 'return',
  CANCELLED = 'cancelled',
  NO_SERVICE = 'no_service',
  RETURN_ACCEPTED = 'return_accepted',
  RETURN_REJECTED = 'return_rejected',
  RETURN_INITIATED = 'return_initiated',
  CONFIRMED = 'confirmed',
  IN_TRANSIT = 'inTransit',
  REFUND_PRICE = 'refund_price',
  REPLACEMENT_ORDER = 'replacement_order',
  RTW_DAMAGE = 'rtw_damage',
  RTW_RTO = 'rtw_rto',
  COMPLETED = 'completed',
  PROCESSING = 'processing',
  APPROVAL_PENDING = 'approval_pending',
  APPROVAL_REJECTED = 'approval_rejected',
  Return_Intransit = 'return_intransit',
}

export enum OrderStatus {
  PLACED = 'placed',
  ORDER_REVIEW = 'order_review',
  OTP_TRIGGERED = 'otp_triggered',
  OTP_VERIFIED = 'otp_verified',
  OTP_EXPIRED = 'otp_expired',
  CANCELLED = 'cancelled',
  FAILED = 'failed',
  PARTIAL = 'partial',
}
