export enum NotificationEventType {
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_SUBMITTED = 'INVOICE_SUBMITTED',
  POINTS_ALLOCATED = 'POINTS_ALLOCATED',
  ORDER_PLACED = 'ORDER_PLACED',
  REWARD_REDEEMED = 'REWARD_REDEEMED',
  PRODUCT_RETURNED = 'PRODUCT_RETURNED',
}
