export enum ScanExceptionType {
  UID_MISMATCH = 'UID_MISMATCH',
  SKU_MISMATCH = 'SKU_MISMATCH',
  QTY_MISMATCH = 'QTY_MISMATCH',
  RATE_MISMATCH = 'RATE_MISMATCH',
  RATE_NOT_AVAILABLE = 'RATE_NOT_AVAILABLE',
  MAPPING_MISMATCH = 'MAPPING_MISMATCH',
}

export enum ScanExceptionStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}