export enum InvoiceStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  SCANNED = 'SCANNED',
  EXPIRED = 'EXPIRED',
  COMPLETED = 'COMPLETED',
}

export enum InvoiceScanStatus {
  NOT_SCANNED = 'NOT_SCANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  SCANNED = 'SCANNED',
  PARTIALLY_SCANNED = 'PARTIALLY_SCANNED',
  FULLY_SCANNED = 'FULLY_SCANNED',
}
