export enum ScanAttemptType {
  VALIDATE_INVOICE = 'VALIDATE_INVOICE',
  SESSION_START = 'SESSION_START',
  SINGLE_SCAN = 'SINGLE_SCAN',
  BULK_SCAN = 'BULK_SCAN',
  REMOVE_SCAN = 'REMOVE_SCAN',
  REMOVE_ALL_SCANS = 'REMOVE_ALL_SCANS',
  SESSION_SUBMIT = 'SESSION_SUBMIT',
  SESSION_CANCEL = 'SESSION_CANCEL',
  SESSION_PROGRESS = 'SESSION_PROGRESS',
  SESSION_PAIRS_LIST = 'SESSION_PAIRS_LIST',
  HISTORY_VIEW = 'HISTORY_VIEW',
}

export enum ValidationOutcome {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  MISMATCH = 'MISMATCH',
}